version: "3.8"
services:
  reverse_proxy:
    image: nginx:stable-alpine
    container_name: reverse_proxy
    depends_on:
      - order-mation-front-end
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf  
    ports:
      - 80:80    
  order-mation-front-end:
    container_name: order-mation-front-end
    image: order-mation-front-end
    build: 
      context: ./order-mation-front-end